language: php
matrix:
  include:
  - php: 7.1
    env: DEPENDENCIES=lowest
  - php: 7.1
    env: DEPENDENCIES=highest
  - php: 7.2
    env: DEPENDENCIES=lowest
  - php: 7.2
    env: DEPENDENCIES=highest

before_script:
  - phpenv config-rm xdebug.ini
  - if [ "${DEPENDENCIES}" = "lowest" ]; then composer update --prefer-lowest --prefer-dist --no-interaction --no-progress; fi;
  - if [ "${DEPENDENCIES}" = "highest" ]; then composer update --prefer-dist --no-interaction --no-progress; fi;

script:
    - vendor/bin/phpcs -s --standard=MO4 src/PHPCodeBrowser/
    - vendor/bin/phpstan analyse --no-progress --level=1 src/PHPCodeBrowser/
    - vendor/bin/phpunit
