name: Simple Nix Flakes powered php ci.

on: [push, pull_request]

jobs:
  ci:

    runs-on: ubuntu-latest

    strategy:
      matrix:
          php: [php73, php74]

    env:
      COMPOSER_BIN: "nix shell .github#env-${{ matrix.php }} --command composer"

    steps:
    - uses: actions/checkout@v2
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0

    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Get Composer cache dir
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(${{ COMPOSER_BIN }} config cache-dir)"
      shell: bash

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - run: |
        rm -fr vendor
        ${{ COMPOSER_BIN }} ci-prepare
        ${{ COMPOSER_BIN }} ci
